# Generated by Django 5.1.2 on 2024-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Mesajlara Resim Ekleyin.'),
        ),
    ]
