# Generated by Django 5.1.2 on 2024-12-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_is_responded_message_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_responded',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
    ]
